# Generated by Django 5.2.4 on 2025-10-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StallRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stall_name', models.CharField(max_length=150)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('cuisine_type', models.CharField(help_text='e.g., Chinese, Italian, Street Food, Beverages', max_length=100)),
                ('stall_requirements', models.TextField(blank=True, help_text='e.g., 2 tables, 1 power outlet, space for deep fryer', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
